{
# 公众号配置
# 公众号appId
"app_id": "wx5cb4682f82a8776a",
# 公众号appSecret
"app_secret": "d902b3e1af76d80be7591cd98c5b8a4a",
# 模板消息id
"template_id": "ooplASfzkr1SeDLkaXjiQgfR_fD7qdppUI4BLBF5or0",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["d902b3e1af76d80be7591cd98c5b8a4a"],
 
# 信息配置
# 和风天气apikey
"weather_key": "46aeb2a9f1ad447899ea6e28d0a2e6c2",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦
"region": "CN101030500",
# 在一起的日子，格式同上，暂不不支持农历
"love_date": "2022-06-03",
# 金句中文，如果设置了，则会显示这里的，如果为空，默认会读取金山的每日金句
"note_ch": "",
# 金句英文
"note_en": ""
}

